---
- name: Restart SSH
  service:
    name: sshd
    state: restarted

- name: Reboot System
  ansible.builtin.reboot:
    test_command: whoami

- name: Update initramfs
  command: update-initramfs -u

- name: Restart Auditd 
  service:
    name: auditd 
    state: restarted