---
- name: Restart SSH
  service:
    name: sshd
    state: restarted

- name: Reboot System
  ansible.builtin.reboot:
    test_command: whoami

- name: Update initramfs
  command: update-initramfs -u

- name: Restart Auditd 
  service:
    name: auditd 
    state: restarted
    
- name: Restart chrony
  systemd:
    name: chrony
    state: restarted
- name: Remount /tmp
  ansible.builtin.command: mount -o remount,noexec /tmp
  listen: Remount /tmp

- name: Remount /dev/shm
  ansible.builtin.command: mount -o remount,noexec /dev/shm
  listen: Remount /dev/shm

- name: Restart systemd-journald
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted

- name: Update GRUB
  ansible.builtin.command: update-grub