- name: Install sudo if missing
  ansible.builtin.apt:
    name: sudo
    state: present
    update_cache: yes
- name: Ensure sudo logs to a custom file
  ansible.builtin.copy:
    dest: /etc/sudoers.d/logfile
    content: |
      Defaults logfile="/var/log/sudo.log"
    owner: root
    group: root
    mode: '0440'
    validate: '/usr/sbin/visudo -cf %s'
  register: sudo_logfile_task
- name: Ensure sudo log file exists
  ansible.builtin.file:
    path: /var/log/sudo.log
    state: file
    owner: root
    group: root
    mode: '0600'
  when: sudo_logfile_task is changed




