- name: Configure cluster.fw - Datacenter
  ansible.builtin.template:
    src: "cluster.fw.j2"
    dest: /etc/pve/firewall/cluster.fw
    #owner: root # no owner/mode not allowed in pmxcfs
    #group: root
    #mode: '0640'
    follow: yes
    unsafe_writes: yes #no tmp file writes because of pmxcfs
  
#- name: Configure Node Firewall
#  ansible.builtin.template:
#    src: "host.fw.j2"
#    dest: "/etc/pve/nodes/{{ ansible_hostname }}/host.fw"
#    #owner: root 
#    #group: root
#    #mode: '0640'
#    follow: yes
#    unsafe_writes: yes

- name: Configure VM Firewall
  ansible.builtin.template:
    src: "vm.fw.j2"
    dest: "{{ '/etc/pve/nodes/' + ansible_hostname + '/host.fw' if item == 'host' else '/etc/pve/firewall/' + item + '.fw' }}"
    follow: yes
    unsafe_writes: yes
  loop: "{{ vm_assignments.keys() | list }}"
  vars:
    assigned_sgs: "{{ security_groups | selectattr('name', 'in', vm_assignments[item]) | list }}"
