- name: Configure /dev/shm mount with noexec
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: '^tmpfs\s+/dev/shm\s+'
    line: 'tmpfs /dev/shm tmpfs rw,nosuid,nodev,noexec,relatime 0 0'
    create: yes
  notify: Remount /dev/shm