- name: Disable and mask rpcbind
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
    masked: true
  loop:
    - rpcbind
    - rpcbind.socket
  when: disable_rpcbind

- name: Disable and mask cluster/HA services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
    masked: true
  loop:
    - corosync
    - pve-ha-lrm
    - pve-ha-crm
  when: disable_pvecluster
