- name: Disable unwanted filesystems
  ansible.builtin.copy:
    dest: "/etc/modprobe.d/{{ item }}.conf"
    content: |
      install {{ item }} /bin/true
    owner: root
    group: root
    mode: '0644'