- name: Load Package facts 
  ansible.builtin.package_facts:
    manager: apt
- name: Set Variables for Grub 
  ansible.builtin.set_fact:
    grub_extra_options: >-
      {{ ('apparmor=1 security=apparmor' if 'apparmor' in ansible_facts.packages else '')}}
      {{ ('audit=1 audit_backlog_limit=8192' if 'auditd' in ansible_facts.packages else '') }}

# name: Log current item being processed
#  ansible.builtin.debug:
#    msg: 'GRUB_CMDLINE_LINUX="{{ grub_extra_options | trim }}"'
- name: update GRUB configuration
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX='
    line: 'GRUB_CMDLINE_LINUX="{{ grub_extra_options | trim }}"'
    backrefs: no
  notify: Update GRUB

#grub_pbkdf2 muss in der Shell erstellt werden und als externe Variable übertragen werden!
#grub-mkpasswd-pbkdf2 -> Setzte Password
- name: GRUB Passwort setzen
  ansible.builtin.template:
    src: grub_password.j2
    dest: /etc/grub.d/50_grub_password
    owner: root
    group: root
    mode: '0600'
  notify: Update GRUB


- name: Secure Permission for GRUB Config
  ansible.builtin.file:
    path: "/boot/grub/grub.cfg"
    owner: "root"
    group: "root"
    mode: "0400"
