- name: Disable USB Storage 
  include_tasks: usb.yml

- name: Configure NTP Services
  include_tasks: configure-ntp.yml

- name: Disable unwanted Filesystems & Modules
  include_tasks: disable-unwanted-filesystems.yml
  loop:
      #Filesystems
      - cramfs
      - freevxfs
      - jffs2
      - hfs
      - hfsplus
      - udf
      #Services
      - rds
      - sctp
      - dccp
      - tipc
      #- squashfs #squashfs is proxmox included
- name: Uninstall unwanted Services
  include_tasks: uninstall-unwanted-services.yml
  loop:
    #- rsync ist in proxmox-ve enthalten!
    - gdm3

- name: Disable unwanted optional Proxmox-Services
  include_tasks: disable-optional-proxmox-services.yml

- name: Configure PVE-Firewall
  include_tasks: configure-pvefirewall.yml
