- name: Set MaxAuthTries to 4
  ansible.posix.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^MaxAuthTries'
    line: 'MaxAuthTries 4'
    state: present
    backrefs: yes
  notify: Restart SSH

- name: Disable X11 forwarding
  ansible.posix.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^X11Forwarding'
    line: 'X11Forwarding no'
    state: present
    backrefs: yes
  notify: Restart SSH

- name: Set strong MAC algorithms
  ansible.posix.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^MACs'
    line: 'MACs hmac-sha2-512,hmac-sha2-256'
    state: present
    backrefs: yes
  notify: Restart SSH

- name: Set ClientAliveInterval to 300 (1-300 allowed)
  ansible.posix.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^ClientAliveInterval'
    line: 'ClientAliveInterval 300'
    state: present
    backrefs: yes
  notify: Restart SSH

- name: Set ClientAliveCountMax to 3 or less
  ansible.posix.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^ClientAliveCountMax'
    line: 'ClientAliveCountMax 3'
    state: present
    backrefs: yes
  notify: Restart SSH

- name: Set LoginGraceTime to 60
  ansible.posix.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^LoginGraceTime'
    line: 'LoginGraceTime 60'
    state: present
    backrefs: yes
  notify: Restart SSH

- name: Disable AllowTcpForwarding 
  ansible.posix.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^AllowTcpForwarding'
    line: 'AllowTcpForwarding no'
    state: present
    backrefs: yes
  notify: Restart SSH

- name: Set MaxStartups to 10:30:100 or more restrictive
  ansible.posix.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^MaxStartups'
    line: 'MaxStartups 10:30:100'
    state: present
    backrefs: yes
  notify: Restart SSH

- name: Disable root login if disable_root is true
  ansible.posix.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
    state: present
    backrefs: yes
  when: disable_root | bool
  notify: Restart SSH

