- name: Ensure sshd_config includes drop-in directory
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^Include\s+/etc/ssh/sshd_config\.d/\*\.conf'
    line: 'Include /etc/ssh/sshd_config.d/*.conf'
    insertafter: '^#?Port '
    state: present
  notify: Restart SSH


- name: Deploy CIS-compliant drop-in config 
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config.d/99-cis.conf
    owner: root
    group: root
    mode: '0600'
  notify: Restart SSH