- name: Log current item being processed
  ansible.builtin.debug:
    msg: "Setting permissions for {{ item.path }} to {{ item.mode }} owned by {{ item.owner }}:{{ item.group }}"

- name: Fix permissions on critical files
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"

    