---
- name: Shutdown target machines safely
  hosts: all
  become: true
  gather_facts: false
  
  tasks:
    - name: Notify about upcoming shutdown
      debug:
        msg: "Shutting down host {{ inventory_hostname }}..."
      when: tasmota_command == 'Power%20off'

    - name: Shutdown the system
      command: shutdown -h now
      async: 1
      poll: 0
      when: tasmota_command == 'Power%20off'

    - name: Wait 1 minutes to shutdown
      ansible.builtin.pause:
        minutes: 1
      when: tasmota_command == 'Power%20off'
  
- name: Schalte Tasmota Steckdose ein/aus
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Steckdose Command über HTTP API
      uri:
        url: "http://{{ tasmota_ip }}/cm?cmnd={{ tasmota_command }}"
        method: GET
        user: "{{ tasmota_user }}"
        password: "{{ tasmota_password }}"
        force_basic_auth: yes
        return_content: yes
      register: result

    - name: Ausgabe des Tasmota-Antwort
      debug:
        var: result.content
    

- name: Checking if Boot was successful
  hosts: all
  become: true
  gather_facts: false
  
  tasks:
    - name: Wait for system to become reachable
      ansible.builtin.wait_for_connection:
        timeout: 900
      when: tasmota_command == 'Power%20on'


    
      
