disable_usb_storage: true
enable_auditd: true
disable_root: false
grub_cmdline_parameter: []
ntp_servers:
    - 0.de.pool.ntp.org
    - 1.de.pool.ntp.org
    - 2.de.pool.ntp.org
    - 3.de.pool.ntp.org
ipsets:
    - name: "internal-net"
      ip:
        - 192.168.1.0/24
        - 192.168.2.0/24
    - name: "management"
      ip: 
        - 192.168.2.163
      
security_groups:
    - name: pve-hostbase
      rules: [
        { "direction": "IN", "action": ACCEPT, "protocol": "tcp", "port": 22 },
        { "direction": "IN", "action": ACCEPT, "protocol": "tcp", "port": 8006, "comment": "WebGUI", "source": "+management"},
        { "direction": "IN", "action": ACCEPT, "protocol": "icmp" }           
      ]
    - name: webserver
      rules: [
        { "direction": "IN", "action": ACCEPT, "protocol": "tcp", "port": 80 },
        { "direction": "IN", "action": ACCEPT, "protocol": "tcp", "port": 443 }        
        ]
    - name: https
      rules: [
        { "direction": "IN", "action": ACCEPT, "protocol": "tcp", "port": 443 }        
        ]
    #IN ACCEPT -p tcp --dport 22
    #IN ACCEPT -p tcp --dport 8006
    #IN ACCEPT -p icmp

vm_assignments:
    "host": 
        - pve-hostbase
    "100": #ID of VM
        - pve-hostbase
        - webserver
    "101":
        - webserver
permitrootlogin: "yes" #'prohibit-password' or 'no'
password_auth: "yes" # or "no"
grub_superuser: grubadmin
disable_ceph: true
disable_rpcbind: true
disable_multipathd: true #iSCSI, SAN, Firebchannel-LUN
disable_pvecluster: true
