---
- name: Install Proxmox CIS Hardening Role
  hosts: all
  gather_facts: true
  become: true
  pre_tasks:
    - name: Install proxmoxer
      ansible.builtin.pip:
        name: proxmoxer
        state: latest #present
      delegate_to: "{{ proxmoxworker | default 'localhost'}}"
  roles:
    - proxmox_cis_hardening