- name: Leere VM für PXE-Boot anlegen
  hosts: all
  gather_facts: false

  vars:
    node: pve-staging
    new_vmid: 110
    vm_name: "win-pxe-{{ new_vmid }}"
    storage: "local-lvm"
    disk_size: "20G"

  tasks:
    - name: PXE-VM erstellen (nur Shell)
      delegate_to: localhost
      community.proxmox.proxmox_kvm:
        #api_host: "{{ node }}"
        api_user: root@pam
        api_password: "{{ root_pw }}"
        api_host: "{{ inventory_hostname }}"
        #password: "{{ root_pw }}"
        node: "{{ node }}"
        vmid: "{{ new_vmid }}"
        name: "{{ vm_name }}"
        net:
          net0: 'virtio,bridge=vmbr1,rate=200'
        cores: 4
        vcpus: 1
        memory: 4096
        shares: 0 #Disable Auto-Balloning
        ostype: win11
        #scsi Hardware Controller
        scsihw: virtio-scsi-single
        #Disk Konfiguration
        scsi:
          scsi0: 'local-lvm:10,format=raw'
        #BIOS UEFI
        bios: ovmf
        #BIOS Type
        #smbios
        #EFI Disk
        efidisk0:
          storage: local-lvm
          format: raw
          efitype: 4m
          pre_enrolled_keys: true
        tpmstate0:
          storage: tpmstate0.storage
          version: 2.0
        #localtime: true # no need ostype = win11 
        protection: true #Enable/disable the protection flag of the VM. This will enable/disable the remove VM and remove disk operations
        startdate: now
        update: "{{ Update }}"
        
    - name: Konfiguriere Disks 
      delegate_to: localhost
      community.proxmox.proxmox_disk:
        api_user: root@pam
        api_password: "{{ root_pw }}"
        api_host: "{{ inventory_hostname }}"
        vmid: "{{ new_vmid }}"
        disk: scsi0
        backup: true
        cache: writeback
        discard: on
        ro: false #ReadOnly
        aio: native
        state: present