- hosts: all
  become: true
  vars:
    user: deploy
  tasks:
    - name: Debug SSH Key 
      debug:
        msg: "{{ final_ssh_pubkey}}"
    - name: Ensure user exists
      ansible.builtin.user:
        name: "{{ user }}"
        shell: /bin/bash
        groups: sudo
        append: yes

    - name: Create .ssh directory
      file:
        path: "/home/{{ user }}/.ssh"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0700'

    - name: Install final SSH key
      authorized_key:
        user: "{{ user }}"
        key: "{{ final_ssh_pubkey }}"
        state: present
    - name: Allow {{ user }} to use sudo without password
      copy:
        dest: "/etc/sudoers.d/{{ user }}"
        content: "{{ user }} ALL=(ALL) NOPASSWD:ALL"
        owner: root
        group: root
        mode: '0440'
