---
- name: "Test um Dinge wie Webhooks, CMDB Einträge etc. zu auszuführen"
  hosts: localhost
  become: false
  tasks:
    - name: Führe whoami aus
      command: whoami
      register: whoami_output

    - name: Output whoami
      debug:
        msg: "Der Benutzer ist: {{ whoami_output.stdout }}"

