---
- name: "Test um Dinge wie Webhooks, CMDB Einträge etc. zu auszuführen"
  hosts: localhost
  become: false #true ist wahrscheinlich nicht möglich
  tasks:
    - name: Führe whoami aus
      command: whoami
      register: whoami_output


