- name: Reboot Hosts
  hosts: all
  become: true
  tasks:
    - name: Reboot system
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible"
        reboot_timeout: rtimeout | default(rtimeout)
        test_command: whoami
