---
- name: all then filter
  hosts: all

  become: true
  vars:
    node_prefix: "rbpcm-node-"

  tasks:
    - name: Nur Hosts mit gewünschter Node-Nummer
      debug:
      #  msg: "Ich bin {{ inventory_hostname }}"
      #when: inventory_hostname == (node_prefix ~ target_node | string)
       msg: "Ich bin {{ node}}"
      when: node == (target_node | string)

    - name: Nur Hosts mit gewünschter Node-Nummer
      debug:
        msg: "Ich bin {{ inventory_hostname }}"
      when: inventory_hostname == (node_prefix ~ target_node | string)
      
    - name: Nur Hosts aus gewünschtem Land
      debug:
        msg: "Land {{ country }} ausgewählt"
      when: country == target_country | default(country)

    - name: Nur Hosts mit gewünschter Node-Nummer STRINGParsing
      debug:
        msg: "Ich bin {{ inventory_hostname }} mit node={{ node }}"
      when: (node | string) == (target_node | default(node) | string)

    - name: Nur Hosts aus gewünschtem Land
      debug:
        msg: "Land {{ country }} ausgewählt"
      when: (country | string) == (target_country | default(country) | string)

- name: try filter first
  hosts: gerade
  tasks:
    - name: Nur Hosts mit gewünschter Node-Nummer
      debug:
      #  msg: "Ich bin {{ inventory_hostname }}"
      #when: inventory_hostname == (node_prefix ~ target_node | string)
       msg: "Ich bin {{ node}}"
      when: node == (target_node | string)

    - name: Nur Hosts mit gewünschter Node-Nummer
      debug:
        msg: "Ich bin {{ inventory_hostname }}"
      when: inventory_hostname == (node_prefix ~ target_node | string)
      
    - name: Nur Hosts aus gewünschtem Land
      debug:
        msg: "Land {{ country }} ausgewählt"
      when: country == target_country | default(country)

    - name: Nur Hosts mit gewünschter Node-Nummer STRINGParsing
      debug:
        msg: "Ich bin {{ inventory_hostname }} mit node={{ node }}"
      when: (node | string) == (target_node | default(node) | string)

    - name: Nur Hosts aus gewünschtem Land
      debug:
        msg: "Land {{ country }} ausgewählt"
      when: (country | string) == (target_country | default(country) | string)

#    - name: update apt packages
#      apt:
#        upgrade: yes
#        update_cache: yes
        