---
- hosts: all

  become: true
  vars:
    node_prefix: "rbpcm-node-"
  tasks:
    - name: Nur Hosts mit gewünschter Node-Nummer
      debug:
      #  msg: "Ich bin {{ inventory_hostname }}"
      #when: inventory_hostname == (node_prefix ~ target_node | string)
       msg: "Ich bin {{ node}}"
      when: node == (target_node | string)

    - name: Nur Hosts aus gewünschtem Land
      debug:
        msg: "Land {{ country }} ausgewählt"
      when: country == target_country | default(country)
#    - name: update apt packages
#      apt:
#        upgrade: yes
#        update_cache: yes
        