---
- hosts: 4

  become: true
  tasks:
    - name: Nur Hosts mit gew체nschter Node-Nummer
      debug:
        msg: "Node {{ node }} ausgew채hlt"
      when: node == target_node | default(node)

    - name: Nur Hosts aus gew체nschtem Land
      debug:
        msg: "Land {{ country }} ausgew채hlt"
      when: country == target_country | default(country)
#    - name: update apt packages
#      apt:
#        upgrade: yes
#        update_cache: yes
        